version: '3'
services:
  nginx:
    restart: always
    image: us.gcr.io/dayinthelife-168402/nginx
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - default
    links: 
      - node:node
    depends_on: 
      - node
    container_name: nginx
  node:
    restart: always
    image: us.gcr.io/dayinthelife-168402/node
    networks:
      - default
    ports: 
      - "8000"
    container_name: node
networks:
  default:
    driver: bridge