#!/bin/bash

# stop and remove all containers
docker stop $(docker ps -q)
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)

# remove all images
docker rmi $(docker images -a -q)

docker-compose build
docker-compose up -d
